- name: Criando security group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security group
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: criando o EC2
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    wait=true
    region={{ region }}
    keypar={{ keypar }}
    count={{ count }}
  register: ec2_created

- name: adicionando instancia 
  add_host: name={{ item.public_ip }} groups=giropops-new
  with_items: "{{ ec2.instances }}"

- name: adicionando a instancia criado no arquivo hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[hpg-maquinas]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: esperando o ssh
  local_action: wait_for
    host:{{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"

- name: adicionando uma tag
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: HPG-teste-maquinas 

