# Copyright (C) 2019 Alcides Goldoni Junior <goldoni@ggaunicamp.com>
# Copyright (C) 2019 Alcides Goldoni Junior <agoldonijr@gmail.com>

---
- name: Ansible tests playbook
  hosts: all
  become: yes 
  become_method: sudo

  tasks:
  #Adding repo for google chrome
    - apt_repository:
        repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        state: present
        filename: google-chrome.list
   #Adding repo for octave 
    - apt_repository:
        repo: deb http://ppa.launchpad.net/octave/stable/ubuntu xenial main
        state: present
        filename: octave
    
    - name: Check and install base packages 
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - octave
        - google-chrome-stable
        - git
        - htop
        - vim
        - screen
        - gcc
        - openssh-server
        - goldendict 
        - pdftk 
        - ispell 
        - kile 
        - maxima 
        - inkscape 
        - eclipse 
        - gparted
        - build-essential 
        - dkms 
        - pstoedit 
        - okular 
        - nfs-common 
        - python-scitools 
        - python-matplotlib 
        - python-sklearn 
        - python-pywt 
        - python-sympy
        - python-scipy
        - python-numpy 
        - python-pymongo 
        - python-opencv 
        - python3-tk
        - libcv-dev 
        - opencv-doc 
        - libhighgui-dev 
        - kdiff3 
        - texlive-full 
        - icedax 
        - id3v2 
        - lame 
        - libflac++6v5 
        - libjpeg-progs 
        - mencoder 
        - regionset 
        - sox 
        - uudeview 
        - vorbis-tools 
        - x264 
        - arj 
        - p7zip 
        - p7zip-full 
        - p7zip-rar 
        - unrar 
        - unace-nonfree 
        - vlc 
        - gimp 
        - screen 
        - htop 
        - cpufrequtils 
        - ntp 
        - aspell 
        - aspell-pt-br 
        - djvulibre-desktop 
        - libclang-dev 
        - cmake 
        - stow 
        - libdbus-1-dev 
        - libcups2 
        - openssl 
        - libcups2-dev 
        - cups-bsd 
        - cups-client 
        - libsane-dev 
        - libcupsimage2-dev 
        - libsnmp-dev 
        - snmp-mibs-downloader 
        - libtool 
        - opencl-headers 
        - lsb-core 
        - mono-devel 
        - gitk 
        - fftw-dev 
        - libfftw3-dev 
        - libeigen3-dev 
        - libcgal-dev 
        - libopenmpi-dev 
        - gnome-session-flashback 
        - x11proto-xf86bigfont-dev 
        - xfstt 
        - t1-xfree86-nonfree 
        - ttf-xfree86-nonfree 
        - ttf-xfree86-nonfree-syriac 
        - xfonts-75dpi 
        - xfonts-100dpi 
        - x11-xfs-utils 
        - xfstt 
        - curl 
        - autoconf 
        - autoconf-archive 
        - autogen 
        - automake 
        - libmnl-dev 
        - uuid-dev 
        - compizconfig-settings-manager 
        - compiz-plugins 
        - libx11-dev
        - libxt-dev
        - vim-gnome 
        - tmux
        - gfortran
