# Copyright (C) 2019 Alcides Goldoni Junior <goldoni@ggaunicamp.com>
# Copyright (C) 2019 Alcides Goldoni Junior <agoldonijr@gmail.com>

---
- name: Ansible run script 
  hosts: all
  become: yes 
  become_method: sudo
  remote_user: manutencao

  tasks:
    - name: Send script
      copy: src="../padronizacao/padronizacaoUbuntu.sh" dest=/home/manutencao mode=0777

    - name: Run a script 
      command: bash /home/manutencao/padronizacaoUbuntu.sh 
